import { EmployeeEntry } from './types';

export const INITIAL_EMPLOYEE_DATA: EmployeeEntry[] = [
  {
    "id": "emp_1002",
    "sl": "1",
    "name": "Md. Monir Hossain Teto",
    "nameBangla": "মোঃ মনির হোসেন টিটো",
    "fatherName": "Ahmed Ullah Bhuiyan",
    "motherName": "Rowshan Ara Begum",
    "dobDay": "1",
    "dobMonth": "6",
    "dobYear": "1969",
    "dob": "1.6.1969",
    "currentPosition": "Joint Director (A & F)",
    "currentDepartment": "Admin",
    "jobId": "1002",
    "joiningDay": "1",
    "joiningMonth": "11",
    "joiningYear": "1989",
    "joiningDate": "1.11.1989",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "7756402579",
    "nomineeName": "Nazma Sultana",
    "nomineeNid": "2356428322",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412001",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_301",
    "sl": "2",
    "name": "Md. Alauddin Sarkar",
    "nameBangla": "মো: আলাউদ্দিন সরকার",
    "fatherName": "Md. Abdul Jabbar Sarker",
    "motherName": "Most.Mayna Begum",
    "dobDay": "1",
    "dobMonth": "1",
    "dobYear": "1965",
    "dob": "1.1.1965",
    "currentPosition": "Asst. Director",
    "currentDepartment": "Publication",
    "jobId": "301",
    "joiningDay": "18",
    "joiningMonth": "1",
    "joiningYear": "1992",
    "joiningDate": "18.1.1992",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "7764813932",
    "nomineeName": "Mrs. Monowara Khatun & Mehedi Hasan Piash",
    "nomineeNid": "9557415297, 6905173891",
    "relation": "Wife. Son",
    "share": "50%, 50%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412002",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_sl_3",
    "sl": "3",
    "name": "Md. Kamal Hossain",
    "nameBangla": "মোঃ কামাল হোসাইন",
    "fatherName": "Md. Altaf Uddin Sikder",
    "motherName": "Mst Momena Begum",
    "dobDay": "10",
    "dobMonth": "2",
    "dobYear": "1971",
    "dob": "10.2.1971",
    "currentPosition": "Joint Director",
    "currentDepartment": "MLP",
    "jobId": "?",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "2017",
    "joiningDate": "1.7.2017",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "2840790279",
    "nomineeName": "Chamely Begum",
    "nomineeNid": "2640837961",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412003",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_302",
    "sl": "4",
    "name": "S. M.Hazrat Ali",
    "nameBangla": "এস.এম. হযরত আলী",
    "fatherName": "Nizam Uddin Shekh",
    "motherName": "Mst. Sofura Begum",
    "dobDay": "31",
    "dobMonth": "12",
    "dobYear": "1976",
    "dob": "31.12.1976",
    "currentPosition": "Production Officer",
    "currentDepartment": "Publication",
    "jobId": "302",
    "joiningDay": "1",
    "joiningMonth": "8",
    "joiningYear": "1994",
    "joiningDate": "1.8.1994",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "7771181067",
    "nomineeName": "Mst. Peara Khatun",
    "nomineeNid": "1470930635",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412004",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_202",
    "sl": "5",
    "name": "Maheara Nipa",
    "nameBangla": "মাহেয়ারা নীপা",
    "fatherName": "Abdul Motin",
    "motherName": "Maruna Matin",
    "dobDay": "13",
    "dobMonth": "1",
    "dobYear": "1969",
    "dob": "13.1.1969",
    "currentPosition": "Logistic Officer",
    "currentDepartment": "NEP",
    "jobId": "202",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "1997",
    "joiningDate": "1.7.1997",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "8671197260",
    "nomineeName": "Md. Motiul Goni",
    "nomineeNid": "7321163433",
    "relation": "Brother",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412005",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_1003",
    "sl": "6",
    "name": "Mesbha Uddin Ahmed",
    "nameBangla": "মেসবাহ উদ্দিন আহমেদ",
    "fatherName": "Jashim Uddin Ahmed",
    "motherName": "Shamsunnhar",
    "dobDay": "27",
    "dobMonth": "12",
    "dobYear": "1977",
    "dob": "27.12.1977",
    "currentPosition": "Joint Director (P)",
    "currentDepartment": "NEP",
    "jobId": "1003",
    "joiningDay": "1",
    "joiningMonth": "2",
    "joiningYear": "1999",
    "joiningDate": "1.2.1999",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "5081981754",
    "nomineeName": "Noureen Sultana",
    "nomineeNid": "6429316281",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412006",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_214",
    "sl": "7",
    "name": "Md. Anisur Rahaman",
    "nameBangla": "মোঃ আনিছুর রহমান",
    "fatherName": "Tara Miah",
    "motherName": "Mst. Sufia Begum",
    "dobDay": "8",
    "dobMonth": "6",
    "dobYear": "1979",
    "dob": "8.6.1979",
    "currentPosition": "Work-Assistant",
    "currentDepartment": "NEP",
    "jobId": "214",
    "joiningDay": "1",
    "joiningMonth": "4",
    "joiningYear": "1999",
    "joiningDate": "1.4.1999",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "1468032576",
    "nomineeName": "Mst. Moriam Begum",
    "nomineeNid": "3268037458",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412007",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_105",
    "sl": "8",
    "name": "Md. Uzzul Hossain",
    "nameBangla": "মোঃ উজ্জ্বল হোসেন",
    "fatherName": "Md. Deloar Hossaion",
    "motherName": "Johura Begum",
    "dobDay": "2",
    "dobMonth": "2",
    "dobYear": "1980",
    "dob": "2.2.1980",
    "currentPosition": "Deputy Director",
    "currentDepartment": "P & E",
    "jobId": "105",
    "joiningDay": "1",
    "joiningMonth": "2",
    "joiningYear": "2001",
    "joiningDate": "1.2.2001",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "19802695047000025",
    "nomineeName": "Rehnuma Reza",
    "nomineeNid": "8242953936",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412008",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_203",
    "sl": "9",
    "name": "Dulal Chakraborty",
    "nameBangla": "দুলাল চক্রবর্ত্তী",
    "fatherName": "Gopal Chakraborty",
    "motherName": "Pranati Chakraborty",
    "dobDay": "8",
    "dobMonth": "3",
    "dobYear": "1969",
    "dob": "8.3.1969",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "203",
    "joiningDay": "1",
    "joiningMonth": "3",
    "joiningYear": "2004",
    "joiningDate": "1.3.2004",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "7798229162",
    "nomineeName": "Shila Chakraborty",
    "nomineeNid": "2848197477",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412009",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_107",
    "sl": "10",
    "name": "Md Sanowar Hossain",
    "nameBangla": "মোঃ সানোয়ার হোসেন",
    "fatherName": "Md. Ansar Ali",
    "motherName": "Rahana Begem",
    "dobDay": "13",
    "dobMonth": "4",
    "dobYear": "1979",
    "dob": "13.4.1979",
    "currentPosition": "Asst. Director",
    "currentDepartment": "Acconnts",
    "jobId": "107",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "2004",
    "joiningDate": "1.7.2004",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "7789879975",
    "nomineeName": "Sonya Akter",
    "nomineeNid": "1491903660",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412010",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_217",
    "sl": "11",
    "name": "Md. Kamal Hossain",
    "nameBangla": "মোঃ কামাল হুসাইন",
    "fatherName": "Md. Furkan Sheikh",
    "motherName": "Mst. Hosna Ara",
    "dobDay": "1",
    "dobMonth": "4",
    "dobYear": "1986",
    "dob": "1.4.1986",
    "currentPosition": "Work-Assistant",
    "currentDepartment": "NEP",
    "jobId": "217",
    "joiningDay": "1",
    "joiningMonth": "2",
    "joiningYear": "2005",
    "joiningDate": "1.2.2005",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "4635701313",
    "nomineeName": "Rima Khatun",
    "nomineeNid": "6455696994",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412011",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_204",
    "sl": "12",
    "name": "Bikash Kumar Chakrabortty",
    "nameBangla": "বিকাশ কুমার চক্রবর্ত্তী",
    "fatherName": "Bimal Kumar Chakrabortty",
    "motherName": "Ela Chakaraboortty",
    "dobDay": "30",
    "dobMonth": "10",
    "dobYear": "1979",
    "dob": "30.10.1979",
    "currentPosition": "Monitoring Officer",
    "currentDepartment": "P & E",
    "jobId": "204",
    "joiningDay": "1",
    "joiningMonth": "1",
    "joiningYear": "2006",
    "joiningDate": "1.1.2006",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "6444375726",
    "nomineeName": "Mollika Bhattacherjee",
    "nomineeNid": "7794402326",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412012",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_119",
    "sl": "13",
    "name": "Md Haris Miah",
    "nameBangla": "মোঃ হারিছ মিয়া",
    "fatherName": "Md. Mir Kashem",
    "motherName": "Maleka Begum",
    "dobDay": "1",
    "dobMonth": "1",
    "dobYear": "1981",
    "dob": "1.1.1981",
    "currentPosition": "Work-Assistant",
    "currentDepartment": "Admin",
    "jobId": "119",
    "joiningDay": "14",
    "joiningMonth": "5",
    "joiningYear": "2007",
    "joiningDate": "14.5.2007",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "2697557402697",
    "nomineeName": "Md. Arif Hossain",
    "nomineeNid": "19913022903000117",
    "relation": "Brother",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412013",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_205",
    "sl": "14",
    "name": "Md. Muzahidul Alam",
    "nameBangla": "মোঃ মুজাহিদুল আলম",
    "fatherName": "Md. Maij Uddin",
    "motherName": "Amana Khutun",
    "dobDay": "29",
    "dobMonth": "11",
    "dobYear": "1984",
    "dob": "29.11.1984",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "205",
    "joiningDay": "5",
    "joiningMonth": "1",
    "joiningYear": "2008",
    "joiningDate": "5.1.2008",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "3295244929",
    "nomineeName": "Fatema Aktar",
    "nomineeNid": "8245680502",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412014",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_216",
    "sl": "15",
    "name": "Ariful Islam Roman",
    "nameBangla": "আরিফুল ইসলাম রোমান",
    "fatherName": "Abdur Rafiqul Islam",
    "motherName": "Selina Islam",
    "dobDay": "12",
    "dobMonth": "2",
    "dobYear": "1980",
    "dob": "12.2.1980",
    "currentPosition": "Work-Assistant",
    "currentDepartment": "NEP",
    "jobId": "216",
    "joiningDay": "2",
    "joiningMonth": "2",
    "joiningYear": "2008",
    "joiningDate": "2.2.2008",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "4168006502",
    "nomineeName": "Rabia Akter",
    "nomineeNid": "7",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412015",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_206",
    "sl": "16",
    "name": "Abdullah Al Khaled",
    "nameBangla": "আবদুল্লাহ আল খালেদ",
    "fatherName": "Atiar Rahman",
    "motherName": "Khaleda Khanom",
    "dobDay": "15",
    "dobMonth": "10",
    "dobYear": "1981",
    "dob": "15.10.1981",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "206",
    "joiningDay": "12",
    "joiningMonth": "7",
    "joiningYear": "2008",
    "joiningDate": "12.7.2008",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "5959011866",
    "nomineeName": "Sultana Kamruz Jahan Chqwdhury",
    "nomineeNid": "8672567990",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412016",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_307",
    "sl": "17",
    "name": "Md. Enamul Haque",
    "nameBangla": "মোঃ এনামুল হক",
    "fatherName": "Md. Tota Miah",
    "motherName": "Adorar Nesa",
    "dobDay": "31",
    "dobMonth": "12",
    "dobYear": "1974",
    "dob": "31.12.1974",
    "currentPosition": "Computer Operator",
    "currentDepartment": "Publication",
    "jobId": "307",
    "joiningDay": "16",
    "joiningMonth": "7",
    "joiningYear": "2008",
    "joiningDate": "16.7.2008",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "5518927727",
    "nomineeName": "Rokeya Begum",
    "nomineeNid": "1927968089",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412017",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_215",
    "sl": "18",
    "name": "Khondoker Shohidul Islm",
    "nameBangla": "খন্দকার শহীদুল ইসলাম",
    "fatherName": "Khondakar Mosaraf Hossain",
    "motherName": "Laily Begum",
    "dobDay": "19",
    "dobMonth": "11",
    "dobYear": "1992",
    "dob": "19.11.1992",
    "currentPosition": "Work-Assistant",
    "currentDepartment": "Admin",
    "jobId": "215",
    "joiningDay": "1",
    "joiningMonth": "6",
    "joiningYear": "2010",
    "joiningDate": "1.6.2010",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "4206430326",
    "nomineeName": "Khondakar Mosaraf Hossain",
    "nomineeNid": "8654422941",
    "relation": "Father",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412018",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_207",
    "sl": "19",
    "name": "Sk. Harun Or Rashid",
    "nameBangla": "শেখ হারুন অর রশীদ",
    "fatherName": "Sk. Khawza Ahamed",
    "motherName": "Mst. Saleha Khatun",
    "dobDay": "10",
    "dobMonth": "2",
    "dobYear": "1978",
    "dob": "10.2.1978",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "207",
    "joiningDay": "3",
    "joiningMonth": "10",
    "joiningYear": "2010",
    "joiningDate": "3.10.2010",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "1904354097",
    "nomineeName": "Sk. Shafin Ahmad & Habiba Haque",
    "nomineeNid": "42223081573. 2693625797150",
    "relation": "Son. Wife",
    "share": "50%, 50%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412019",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_303",
    "sl": "20",
    "name": "Sonjoy Panday",
    "nameBangla": "সঞ্জয় পান্ডে",
    "fatherName": "Sudhir Ranjan Panday",
    "motherName": "Asha Lata Panday",
    "dobDay": "20",
    "dobMonth": "1",
    "dobYear": "1983",
    "dob": "20.1.1983",
    "currentPosition": "Marketing Officer",
    "currentDepartment": "Publication",
    "jobId": "303",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "2011",
    "joiningDate": "1.7.2011",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "9107461270",
    "nomineeName": "Sudha Rani Mondol",
    "nomineeNid": "7757467027",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412020",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_309",
    "sl": "21",
    "name": "Biplab Barai",
    "nameBangla": "বিপ্লব  বাড়ৈ",
    "fatherName": "Bhavesh Chondra Barai",
    "motherName": "Khana Barai",
    "dobDay": "3",
    "dobMonth": "7",
    "dobYear": "1984",
    "dob": "3.7.1984",
    "currentPosition": "Work-Assistant",
    "currentDepartment": "Publication",
    "jobId": "309",
    "joiningDay": "1",
    "joiningMonth": "9",
    "joiningYear": "2011",
    "joiningDate": "1.9.2011",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "9554583501",
    "nomineeName": "Nandita Rani Halder",
    "nomineeNid": "1514206703",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412021",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_126",
    "sl": "22",
    "name": "Zamal Hossain",
    "nameBangla": "জামাল হোসেন",
    "fatherName": "Md. Nazrul Islam",
    "motherName": "Banuara Khatun",
    "dobDay": "5",
    "dobMonth": "10",
    "dobYear": "1988",
    "dob": "5.10.1988",
    "currentPosition": "Security Guard",
    "currentDepartment": "Admin",
    "jobId": "126",
    "joiningDay": "5",
    "joiningMonth": "9",
    "joiningYear": "2011",
    "joiningDate": "5.9.2011",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "5055152325",
    "nomineeName": "Mst. Shahanaj Parvin",
    "nomineeNid": "9162083266",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412022",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_121",
    "sl": "23",
    "name": "Md. Fazlul Haque",
    "nameBangla": "মোঃ ফজলুল.হক খান",
    "fatherName": "Md. Jamdhar Ali Khan",
    "motherName": "Jamila Khatun",
    "dobDay": "10",
    "dobMonth": "7",
    "dobYear": "1977",
    "dob": "10.7.1977",
    "currentPosition": "Electrician",
    "currentDepartment": "Admin",
    "jobId": "121",
    "joiningDay": "1",
    "joiningMonth": "2",
    "joiningYear": "2012",
    "joiningDate": "1.2.2012",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "6419454001",
    "nomineeName": "Taslima Yeasmine",
    "nomineeNid": "4613765363",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412023",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_208",
    "sl": "24",
    "name": "Md. Abdul Kader",
    "nameBangla": "মোঃ আবদুল কাদের",
    "fatherName": "Md. Abdul Haque",
    "motherName": "Mst Rehena Begum",
    "dobDay": "1",
    "dobMonth": "6",
    "dobYear": "1984",
    "dob": "1.6.1984",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "208",
    "joiningDay": "1",
    "joiningMonth": "3",
    "joiningYear": "2012",
    "joiningDate": "1.3.2012",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "4628133011",
    "nomineeName": "Sadia Afrin",
    "nomineeNid": "6417166052",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412024",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_128",
    "sl": "25",
    "name": "Md. Babul Hossain",
    "nameBangla": "মোঃ বাবুল হোসেন",
    "fatherName": "Tajem Dafadar",
    "motherName": "Halima Begum",
    "dobDay": "15",
    "dobMonth": "8",
    "dobYear": "1971",
    "dob": "15.8.1971",
    "currentPosition": "Security Guard",
    "currentDepartment": "Admin",
    "jobId": "128",
    "joiningDay": "4",
    "joiningMonth": "5",
    "joiningYear": "2013",
    "joiningDate": "4.5.2013",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "3251651133",
    "nomineeName": "Mst. Jahanara Begum",
    "nomineeNid": "0412876308743",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412025",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_135",
    "sl": "26",
    "name": "Mst. Minu Khatun",
    "nameBangla": "মোছাঃ মিনু খাতুন",
    "fatherName": "Sadu Malita",
    "motherName": "Sabuj Jan",
    "dobDay": "21",
    "dobMonth": "2",
    "dobYear": "1968",
    "dob": "21.2.1968",
    "currentPosition": "Cleaner",
    "currentDepartment": "Admin",
    "jobId": "135",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "2014",
    "joiningDate": "1.7.2014",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "9558970811",
    "nomineeName": "Md. Ebrahim Hossain",
    "nomineeNid": "7613921669057",
    "relation": "Son",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412026",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_201",
    "sl": "27",
    "name": "Mahmud Hossain",
    "nameBangla": "মাহমুদ হোসেন",
    "fatherName": "Md. Mofazzal Haque",
    "motherName": "Monowara Haque",
    "dobDay": "6",
    "dobMonth": "8",
    "dobYear": "1981",
    "dob": "6.8.1981",
    "currentPosition": "Logistic Officer",
    "currentDepartment": "NEP",
    "jobId": "201",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "2014",
    "joiningDate": "1.7.2014",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "9139131156",
    "nomineeName": "Mst. Sirina Khatun",
    "nomineeNid": "5065589078",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412027",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_209",
    "sl": "28",
    "name": "Jahangir Hossain",
    "nameBangla": "জাহাঙ্গীর হোসেন",
    "fatherName": "Md. Abul Hossain Munshi",
    "motherName": "Aysha Khatun",
    "dobDay": "1",
    "dobMonth": "3",
    "dobYear": "1988",
    "dob": "1.3.1988",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "209",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "2014",
    "joiningDate": "1.7.2014",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "7336283705",
    "nomineeName": "Afsana Akter Bithi",
    "nomineeNid": "7357945661",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412028",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_218",
    "sl": "29",
    "name": "Md. Faruq Hossain",
    "nameBangla": "মোঃ ফারুক হোসেন",
    "fatherName": "Md. Mohidur Rahman",
    "motherName": "Shefali Bibi",
    "dobDay": "2",
    "dobMonth": "1",
    "dobYear": "1985",
    "dob": "2.1.1985",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "218",
    "joiningDay": "1",
    "joiningMonth": "7",
    "joiningYear": "2014",
    "joiningDate": "1.7.2014",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "6850041325",
    "nomineeName": "Rabeya Khatun",
    "nomineeNid": "5518503981",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412029",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_306",
    "sl": "30",
    "name": "Shre Panonath Dus",
    "nameBangla": "শ্রী পাননাথ দাস",
    "fatherName": "Shre Pandav Chandra Das",
    "motherName": "Sarla Rani Das",
    "dobDay": "15",
    "dobMonth": "6",
    "dobYear": "1970",
    "dob": "15.6.1970",
    "currentPosition": "Cleaner",
    "currentDepartment": "Publication",
    "jobId": "306",
    "joiningDay": "1",
    "joiningMonth": "8",
    "joiningYear": "2014",
    "joiningDate": "1.8.2014",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "3706037672",
    "nomineeName": "Sangita Rani Das",
    "nomineeNid": "9553022063",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412030",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_111",
    "sl": "31",
    "name": "Tania Afroz",
    "nameBangla": "তানিয়া আফরোজ",
    "fatherName": "Md. Sadek Hossain",
    "motherName": "Shahana Begum",
    "dobDay": "11",
    "dobMonth": "3",
    "dobYear": "1988",
    "dob": "11.3.1988",
    "currentPosition": "Information Officer",
    "currentDepartment": "P & E",
    "jobId": "111",
    "joiningDay": "30",
    "joiningMonth": "8",
    "joiningYear": "2014",
    "joiningDate": "30.8.2014",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "5994178639",
    "nomineeName": "Mehedi Rayhan Nadim",
    "nomineeNid": "3293685511",
    "relation": "Husband",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412031",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_132",
    "sl": "32",
    "name": "Md. Kabir Hossain",
    "nameBangla": "মোঃ কবির হোসেন",
    "fatherName": "Ali Azad",
    "motherName": "Kohinoor Begum",
    "dobDay": "1",
    "dobMonth": "1",
    "dobYear": "1986",
    "dob": "1.1.1986",
    "currentPosition": "Cleaner/Security Guard",
    "currentDepartment": "Admin",
    "jobId": "132",
    "joiningDay": "6",
    "joiningMonth": "11",
    "joiningYear": "2014",
    "joiningDate": "6.11.2014",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "6855862394",
    "nomineeName": "Amena Begum",
    "nomineeNid": "5505835396",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412032",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_113",
    "sl": "33",
    "name": "Sadia Afroz Nishat",
    "nameBangla": "সাদিয়া আফরোজ নিশাত",
    "fatherName": "Mohamad Aminul Hoq",
    "motherName": "Rokeya Hoq",
    "dobDay": "1",
    "dobMonth": "3",
    "dobYear": "1983",
    "dob": "1.3.1983",
    "currentPosition": "Assistant Librarian",
    "currentDepartment": "Libarary",
    "jobId": "113",
    "joiningDay": "20",
    "joiningMonth": "11",
    "joiningYear": "2014",
    "joiningDate": "20.11.2014",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "1470106145",
    "nomineeName": "Aniqa Zahin",
    "nomineeNid": "4661286577",
    "relation": "Daughter",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412033",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_133",
    "sl": "34",
    "name": "Md. Polash Akhan",
    "nameBangla": "মোঃ পলাশ আকন",
    "fatherName": "Md. Atahhar Ali",
    "motherName": "Nessa Begum",
    "dobDay": "7",
    "dobMonth": "3",
    "dobYear": "1993",
    "dob": "7.3.1993",
    "currentPosition": "Cleaner",
    "currentDepartment": "Admin",
    "jobId": "133",
    "joiningDay": "1",
    "joiningMonth": "4",
    "joiningYear": "2015",
    "joiningDate": "1.4.2015",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "7317950280",
    "nomineeName": "Md. Atahar Ali",
    "nomineeNid": "2691651185756",
    "relation": "Father",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412034",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_1213",
    "sl": "35",
    "name": "Uttam Kumar Mandal",
    "nameBangla": "উত্তম কুমার মন্ডল",
    "fatherName": "Gurudas Mondal",
    "motherName": "Anita Rani Mondal",
    "dobDay": "7",
    "dobMonth": "5",
    "dobYear": "1987",
    "dob": "7.5.1987",
    "currentPosition": "Stor Keeper",
    "currentDepartment": "Admin",
    "jobId": "1213",
    "joiningDay": "1",
    "joiningMonth": "3",
    "joiningYear": "2016",
    "joiningDate": "1.3.2016",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "8210719798162",
    "nomineeName": "Gurudas Mondal",
    "nomineeNid": "8210719798035",
    "relation": "Father",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412035",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_211",
    "sl": "36",
    "name": "Md. Aktharuzzaman Rashed",
    "nameBangla": "আখতারুজ্জামান রাশেদ",
    "fatherName": "Md. Abul Hossain Sarker",
    "motherName": "Most. Rowshan Ara Begum",
    "dobDay": "1",
    "dobMonth": "1",
    "dobYear": "1988",
    "dob": "1.1.1988",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "211",
    "joiningDay": "10",
    "joiningMonth": "8",
    "joiningYear": "2016",
    "joiningDate": "10.8.2016",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "1468419278",
    "nomineeName": "Ashrafi Siddika Bonny",
    "nomineeNid": "6893423985",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412036",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_106",
    "sl": "37",
    "name": "Md. Firoz Alam",
    "nameBangla": "মোঃ ফিরোজ আলম",
    "fatherName": "Md. Abdul Hafiz",
    "motherName": "Ummy Kulsum",
    "dobDay": "10",
    "dobMonth": "1",
    "dobYear": "1988",
    "dob": "10.1.1988",
    "currentPosition": "Asst. Director",
    "currentDepartment": "Admin",
    "jobId": "106",
    "joiningDay": "1",
    "joiningMonth": "1",
    "joiningYear": "2018",
    "joiningDate": "1.1.2018",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "5994493897",
    "nomineeName": "Rubyat Sultana",
    "nomineeNid": "5989046395",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412037",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_171",
    "sl": "38",
    "name": "Md. Shaiful Islam",
    "nameBangla": "মোঃ সাইফুল ইসলাম",
    "fatherName": "Md. Esharat Ali",
    "motherName": "Shahida Khatun",
    "dobDay": "15",
    "dobMonth": "2",
    "dobYear": "1985",
    "dob": "15.2.1985",
    "currentPosition": "Accounts Officer",
    "currentDepartment": "Acconnts",
    "jobId": "171",
    "joiningDay": "1",
    "joiningMonth": "1",
    "joiningYear": "2018",
    "joiningDate": "1.1.2018",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "7774609510",
    "nomineeName": "Mst. Mahmuda Yeasmin",
    "nomineeNid": "1913152367",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412038",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_sl_39",
    "sl": "39",
    "name": "Sourov Bhadra",
    "nameBangla": "সৌরভ ভদ্র",
    "fatherName": "Amal Krishna Bhadra",
    "motherName": "Bina Rani Bhadra",
    "dobDay": "12",
    "dobMonth": "1",
    "dobYear": "1985",
    "dob": "12.1.1985",
    "currentPosition": "Program Officer",
    "currentDepartment": "NEP",
    "jobId": "",
    "joiningDay": "1",
    "joiningMonth": "1",
    "joiningYear": "2018",
    "joiningDate": "1.1.2018",
    "status": "Implementation Staff",
    "nationality": "Bangladeshi",
    "nid": "19852691648089987",
    "nomineeName": "",
    "nomineeNid": "",
    "relation": "",
    "share": "",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412039",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_115",
    "sl": "40",
    "name": "Wajib",
    "nameBangla": "ওয়াজিব",
    "fatherName": "Md. Sasab Ali",
    "motherName": "Mst. Manjura Akter",
    "dobDay": "1",
    "dobMonth": "1",
    "dobYear": "1996",
    "dob": "1.1.1996",
    "currentPosition": "Asst. Cameraman",
    "currentDepartment": "Admin",
    "jobId": "115",
    "joiningDay": "1",
    "joiningMonth": "5",
    "joiningYear": "2018",
    "joiningDate": "1.5.2018",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "7361153088",
    "nomineeName": "Sultana Akter",
    "nomineeNid": "7811128045",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412040",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_122",
    "sl": "41",
    "name": "Md. Manohar Badsha",
    "nameBangla": "মোঃ মনোহর বাদশা",
    "fatherName": "Md. Ashkar Ali",
    "motherName": "Mst. Khaleda Begum",
    "dobDay": "1",
    "dobMonth": "1",
    "dobYear": "1988",
    "dob": "1.1.1988",
    "currentPosition": "Electrician",
    "currentDepartment": "Admin",
    "jobId": "122",
    "joiningDay": "1",
    "joiningMonth": "1",
    "joiningYear": "2021",
    "joiningDate": "1.1.2021",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "9312815174157",
    "nomineeName": "Shamima Nasrin",
    "nomineeNid": "9312815175354",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412041",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_129",
    "sl": "42",
    "name": "Humayun Kabir",
    "nameBangla": "হুমায়ুন কবির",
    "fatherName": "Tofazzal Hossain Liton",
    "motherName": "Mst. Anufa",
    "dobDay": "15",
    "dobMonth": "10",
    "dobYear": "2001",
    "dob": "15.10.2001",
    "currentPosition": "Security Guard",
    "currentDepartment": "Admin",
    "jobId": "129",
    "joiningDay": "21",
    "joiningMonth": "11",
    "joiningYear": "2021",
    "joiningDate": "21.11.2021",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "7811131288",
    "nomineeName": "Fahima Jahan Shimu",
    "nomineeNid": "6911224283",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412042",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_134",
    "sl": "43",
    "name": "Nayon Halder",
    "nameBangla": "নয়ন হালদার",
    "fatherName": "Anil Halder",
    "motherName": "Shikha Mondal",
    "dobDay": "2",
    "dobMonth": "3",
    "dobYear": "1995",
    "dob": "2.3.1995",
    "currentPosition": "Cleaner",
    "currentDepartment": "Admin",
    "jobId": "134",
    "joiningDay": "14",
    "joiningMonth": "12",
    "joiningYear": "2021",
    "joiningDate": "14.12.2021",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "2402512806",
    "nomineeName": "Anil Halder",
    "nomineeNid": "8658623478",
    "relation": "Father",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412043",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_116",
    "sl": "44",
    "name": "Palash Das",
    "nameBangla": "পলাশ দাস",
    "fatherName": "Kishore Das",
    "motherName": "Kanan Das",
    "dobDay": "12",
    "dobMonth": "6",
    "dobYear": "1988",
    "dob": "12.6.1988",
    "currentPosition": "Sound Technician",
    "currentDepartment": "Admin",
    "jobId": "116",
    "joiningDay": "1",
    "joiningMonth": "6",
    "joiningYear": "2022",
    "joiningDate": "1.6.2022",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "6710223263829",
    "nomineeName": "Puja Das",
    "nomineeNid": "20016721604131852",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412044",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_105",
    "sl": "45",
    "name": "Md. Jamshed Miah",
    "nameBangla": "মোঃ জামশেদ মিয়া",
    "fatherName": "Md. Joynal",
    "motherName": "Amena Begum",
    "dobDay": "1",
    "dobMonth": "1",
    "dobYear": "2000",
    "dob": "1.1.2000",
    "currentPosition": "Driver",
    "currentDepartment": "Admin",
    "jobId": "105",
    "joiningDay": "1",
    "joiningMonth": "8",
    "joiningYear": "2022",
    "joiningDate": "1.8.2022",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "2855850398",
    "nomineeName": "Amena Begum",
    "nomineeNid": "2826110054",
    "relation": "Mother",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412045",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  },
  {
    "id": "emp_153",
    "sl": "46",
    "name": "Md. Masodur Rahman",
    "nameBangla": "মোঃ মাসুদুর রহমান",
    "fatherName": "Md. Tofazal Hossain",
    "motherName": "Mst. Majada Bagum",
    "dobDay": "4",
    "dobMonth": "4",
    "dobYear": "1980",
    "dob": "4.4.1980",
    "currentPosition": "Driver",
    "currentDepartment": "Admin",
    "jobId": "153",
    "joiningDay": "1",
    "joiningMonth": "8",
    "joiningYear": "2023",
    "joiningDate": "1.8.2023",
    "status": "Support Staff",
    "nationality": "Bangladeshi",
    "nid": "9148808075",
    "nomineeName": "Mst. Asia Begum",
    "nomineeNid": "8234781527",
    "relation": "Wife",
    "share": "100%",
    "minorOnBehalf": "",
    "pfAcNo": "PF202412046",
    "remarks": "",
    "photoURL": "",
    "createdBy": "system",
    "createdByName": "System Seeder",
    "createdByEmail": "system@bskbd.org"
  }
];
